services:
  - type: web
    name: backend
    env: docker
    plan: free
    autoDeploy: false
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    startCommand: uvicorn app:app --reload --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
    disk:
      name: chroma_db
      mountPath: /app/chroma_db
      sizeGB: 1
